---

- name: Configure option values in /etc/locale.gen file.
  lineinfile:
    dest: /etc/locale.gen
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    insertafter: EOF
    state: present
  with_items: "{{ locale_options }}"

- name: Generate Locale
  command: locale-gen de_CH.UTF-8


- name: Set Locale
  command: update-locale LC_ALL=de_CH.UTF-8 LANG=de_CH.UTF-8


- name: set /etc/timezone
  template:
    src: timezone
    dest: /etc/timezone

- name: Switch keyboard layout to DE
  lineinfile:
    dest: /etc/default/keyboard
    regexp: XKBLAYOUT
    line: 'XKBLAYOUT="de_ch"'
