#!/usr/bin/env bash

if [[ $1 == '' || $2 == '' ]]; then
    printf 'argument missing\n'
    printf 'arg1: rolename\n'
    printf 'arg2: your initials\n'
    exit 1
fi

role=${1}
initials=${2}

meta_file="${role}/meta/main.yml"

molecule init role -r "${role}" -d docker
sed -i "s/your name/${initials}/" ${meta_file}
sed -i "s/your description/${role}/" ${meta_file}
sed -i 's/your company (optional)/LBA Corp./' ${meta_file}
sed -i 's/license (GPLv2, CC-BY, etc)/MIT/' ${meta_file}
sed -i '/dependencies\: \[\]/d' ${meta_file}
sed -i '/^$/d' ${meta_file}
sed -i '/  #/d' ${meta_file}
sed -i '/# /d' ${meta_file}
